name: LambdaTest Playwright

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests on LambdaTest
        env:
          LAMBDA_USERNAME: ${{ secrets.LAMBDA_USERNAME }}
          LAMBDA_ACCESS_KEY: ${{ secrets.LAMBDA_ACCESS_KEY }}
          BASE_URL: https://dev.ashurityhealth.com/login
        run: |
          npx playwright test --config=playwright.config.lt.ts
